name: Markdown to HTML (Only Changed Files)

on:
  push:
    branches:
      - main
    paths:
      - 'submissions/*.md'

permissions:
  contents: write

jobs:
  convert-markdown:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Convert Only Changed Markdown to HTML
        run: |
          pip install gitpython
          python3 md_to_html_only_changed.py

      - name: Commit and push HTML files
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add html/
          git commit -m "Auto-generate HTML from changed markdown files"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
