name: Convert Markdown --> HTML

on:
  push:
    branches:
      - main
    paths:
      - 'docs/users/markdown/*.md'

permissions:
  contents: write
  pull-requests: write

jobs:
  convert-markdown:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Print working directory and list markdown files
        run: |
          pwd
          echo "Markdown files:"
          ls -l docs/users/markdown || echo "No markdown files found"
          echo "Profiles directory:"
          mkdir -p docs/users/profiles
          ls -l docs/users/profiles || echo "No profiles yet"

      - name: Run python script to convert markdown to HTML
        run: |
          echo "Running md2html.py..."
          python3 .github/scripts/md2html.py
          echo "Listing generated HTML:"
          ls -l docs/users/profiles || echo "No HTML files generated"

      - name: Create Pull Request with generated HTML
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Auto-generated HTML page(s) from markdown"
          branch: auto/html-gen-${{ github.run_id }}
          title: "Generate HTML from merged markdown"
          base: main
          add-paths: |
            docs/users/profiles/*.html
